version: '3.8'
services:
  app:
    build: ./src
    container_name: internet-shop
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shopdb
      - SPRING_DATASOURCE_USERNAME=shopuser
      - SPRING_DATASOURCE_PASSWORD=shoppass
    depends_on:
      - db
    networks:
      - monitoring
  db:
    image: postgres:15
    container_name: shop-postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${shopdb}
      - POSTGRES_USER=${dbuser}
      - POSTGRES_PASSWORD={T756389b}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alert.rules.yml:/etc/prometheus/alert.rules.yml
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD={T756389b}
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - '9100:9100'
    networks:
      - monitoring
volumes:
  postgres_data:
  grafana_data:
networks:
  monitoring:
    driver: bridge