spring.application.name=internet-shop
server.port=8080

spring.datasource.url=jdbc:postgresql://db:5432/shopdb
spring.datasource.username=shopuser
spring.datasource.password=shoppass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=prometheus,health,info,metrics
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=${spring.application.name}